module:
  imports:
    - path: github.com/fengliwu/fengli-hugo-blox
  mounts:
    - source: blox
      target: layouts/partials/blocks/
      includeFiles: '**.html'
    - source: blox
      target: assets/dist/community/blox/
      includeFiles: '**.css'
